"use client";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const { push } = useRouter();
  useEffect(() => {
    push("/home");
  }, []);

  return (
    <>
      <Head>
        <title>Bumper to Bumper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} />
    </>
  );
}
